### ISSUE TITLE
[ToDo] Basic App

### ISSUE THREAD

**Issue by ElryWeeb** [ElryWeeb/Kavizo#1]
- [ ] Finish up the Startup Page.
- [ ] Create a Setup Page to enter URL, Login & Password.
- [ ] Test the Setup / Startup Page.
- [ ] Create a Main Page with 3 Tabs (Reading, Library & Settings).
- [ ] Create the Library Tab, that first shows all librarys of type 0 = manga & 1 = comics. (Unless its only 1, then directly load all Series)
- [ ] Load all Content of that Library that is of type 0 = Image & 1 = Archive.
- [ ] Create the Reading Tab, which is basically everything on their Home Tab, that is of type 0 = Image & 1 = Archive.
- [ ] Create the Settings Tab, which houses Reading Direction, Software Back Button & Log Out. (More coming with Development).
- [ ] When clicking on a Series, save that info &move to the Reading Page.
- [ ] On the Reading Page, check the read Chapter of that Series and then load that chapter & the current read image.
- [ ] Next load the Reading direction and Place invisible Buttons matching Horizontal or Vertial Readin Mode.
- [ ] Create the invisible Back button in the middle of the screen. (If enabled.)
- [ ] When clicking on the Navigation Buttons, load the next / previous image. (Handle no prev/next file)
